name: Update Trend Data

# 워크플로우 임시 비활성화 (필요시 주석 해제)
# on:
#   schedule:
#     - cron: '0 */6 * * *'  # 6시간마다 실행
#   workflow_dispatch:  # 수동 트리거 허용

# 수동 트리거만 활성화 (스케줄은 비활성화)
on:
  workflow_dispatch:  # 수동 트리거만 허용

jobs:
  update-trends:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytrends requests beautifulsoup4
      
      - name: Create required directories
        run: |
          mkdir -p ./src/main/resources
      
      - name: Run update script
        run: |
          chmod +x ./src/main/resources/update_trends.sh
          bash ./src/main/resources/update_trends.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          # 변경사항 확인
          if [[ -n $(git status -s) ]]; then
            git add src/main/resources/trending_keywords.json
            git add src/main/resources/update_trends.log || true
            git commit -m "Update trend data $(date +'%Y-%m-%d %H:%M:%S')"
            git push
            echo "트렌드 데이터가 업데이트되었습니다."
          else
            echo "변경된 파일이 없습니다."
          fi
          
      - name: Update trends on server (if needed)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          # 여기에 서버에 SSH 접속하여 트렌드 데이터를 업데이트하는 스크립트를 추가할 수 있습니다.
          # 서버 접속이 필요한 경우 GitHub Secrets를 사용하여 인증 정보를 안전하게 저장하세요.
          echo "서버 업데이트 준비 완료 (필요시 아래 주석 해제)"
          
          # 예시:
          # SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
          # echo "$SSH_PRIVATE_KEY" > key.pem
          # chmod 600 key.pem
          # ssh -i key.pem -o StrictHostKeyChecking=no user@server.com "cd /path/to/app && ./src/main/resources/update_trends.sh" 